### ISSUE TITLE
Proofs breakable per default

### ISSUE THREAD

**Issue by sebaseb98** [jbirnick/typst-great-theorems#1]
Very nice package! I substituted ctheorems by it and it worked pretty well. Their default boxes have a slight radius which I personally prefer over sharp corners, but that's a matter of taste I would say.

The small issue I encountered was that I had to set 

`#let proof = proofblock(breakable: true)`

And at least from things I've worked on I never encountered situations where I wished for non-breakable proofs.  I would suggest to make this the default, to make it more intuitive.
I guess it'll be a quick fix :)

**Comment by jbirnick** [comment]
Hey, thank you very much!

As you probably know, you can easily put a radius on your theorems:
```typ
#let remark = mathblock(
  blocktitle: "Remark",
  prefix: [_Remark._],
  inset: 5pt,
  fill: lime,
  radius: 5pt,
)
```
Indeed I chose that the default is no inset/radius/fill because this is the default in books and papers.

If you want to have a common style for all your theorem, lemma, remark, etc. environments and you don't want to write boilerplate code, you can define your own defaults like this:
```typ
#let my_mathblock = mathblock.with(fill: yellow, radius: 5pt, inset: 5pt)

#let theorem = my_mathblock(...)
#let lemma = my_mathblock(...)
#let remark = my_mathblock(...)
...
```

Now to your main point, the breakable-ness of theorems and proofs. Indeed, the default in v0.1.0 is that `mathblock`s are not breakable. (This is due to the changes that were introduced in Typst 0.12, thanks @PgBiel for mentioning this [here](https://github.com/typst/typst/issues/4633#issuecomment-2423259676).)

I have fixed it, and now _all_ `mathblock`s are breakable by default. If you don't want your theorems to be breakable, just pass `breakable: false` to them.

The changes are now in v0.1.1 and I have already [submitted them](https://github.com/typst/packages/pull/1135), so v0.1.1 will be available on the Typst Universe in the next 1-2 days.

Thank you for using great-theorems and have a nice day! :)
